src/main/java/smash/teams/be/model/errorLog/ErrorLog.java
src/main/java/smash/teams/be/model/loginLog/LoginLog.java
src/main/java/smash/teams/be/model/schedule/Schedule.java
src/main/java/smash/teams/be/model/team/Team.java
src/main/java/smash/teams/be/model/user/User.java

Background
- 혼동을 줄이기 위해 원래 의미를 가진 단어로 변수명 변경
Changes
- 모델 별로 Validation 추가
- 일부 컬럼명 수정

Fix: 모델 별 Validation 추가

---

src/main/java/smash/teams/be/model/schedule/Schedule.java
src/main/java/smash/teams/be/model/schedule/Status.java
src/main/java/smash/teams/be/model/schedule/Type.java

PR: Schedule 엔티티 컬럼 및 enum 수정

---

src/main/java/smash/teams/be/controller/ScheduleController.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/dto/schedule/ScheduleResponse.java
src/main/java/smash/teams/be/model/schedule/Schedule.java
src/main/java/smash/teams/be/model/schedule/ScheduleRepository.java
src/main/java/smash/teams/be/model/user/User.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java
src/test/java/smash/teams/be/core/WithMockUser.java
src/test/java/smash/teams/be/core/WithMockUserFactory.java
src/test/java/smash/teams/be/model/schedule/ScheduleRepositoryTest.java
src/test/java/smash/teams/be/service/ScheduleServiceTest.java

PR: 유저 스케쥴 내역 조회 구현 및 테스트 완료

---

src/main/java/smash/teams/be/controller/AdminContoller.java
src/main/java/smash/teams/be/controller/ScheduleController.java
src/main/java/smash/teams/be/core/advice/LogAdvice.java
src/main/java/smash/teams/be/core/advice/ValidAdvice.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/core/filter/TempFilter.java
src/main/java/smash/teams/be/dto/admin/AdminResponse.java
src/main/java/smash/teams/be/model/schedule/ScheduleRepository.java
src/main/java/smash/teams/be/model/user/UserQueryRepository.java
src/main/java/smash/teams/be/service/AdminService.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/test/java/smash/teams/be/controller/AdminContollerUnitTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java
src/test/java/smash/teams/be/service/AdminServiceTest.java

유저 권한 설정 페이지 조회(탭 이동, 검색 기능 포함) 구현 및 테스트 완료
rebase merge 이후 일부 테스트 관련 오류 수정

PR: 유저 권한 설정 페이지 조회(탭 이동, 검색 기능 포함) 구현 및 테스트 완료

---

src/main/java/smash/teams/be/controller/ScheduleController.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/core/util/DateUtil.java
src/main/java/smash/teams/be/dto/schedule/ScheduleResponse.java
src/main/java/smash/teams/be/model/schedule/ScheduleRepository.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java
src/test/java/smash/teams/be/core/MyWithMockUser.java
src/test/java/smash/teams/be/core/MyWithMockUserFactory.java
src/test/java/smash/teams/be/model/schedule/ScheduleRepositoryTest.java
src/test/java/smash/teams/be/service/ScheduleServiceTest.java

PR: 메인 페이지 조회 구현 및 테스트 완료 

---

src/test/java/smash/teams/be/controller/AdminControllerUnitTest.java
src/test/java/smash/teams/be/service/AdminServiceTest.java

PR: 팀 삭제 컨트롤러 유닛 테스트 완료

---

src/main/java/smash/teams/be/controller/AdminController.java
src/test/java/smash/teams/be/controller/AdminControllerUnitTest.java

PR: 관리자 권한 API path 수정

---

src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/dto/schedule/ScheduleResponse.java
src/main/java/smash/teams/be/dto/user/UserResponse.java
src/main/java/smash/teams/be/service/UserService.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java
src/test/java/smash/teams/be/controller/UserControllerUnitTest.java
src/test/java/smash/teams/be/service/UserServiceTest.java

내정보 조회 구현, 테스트 완료 (컨트롤러, 서비스만)

PR: 내정보 조회 구현, 테스트 완료

---

src/main/java/smash/teams/be/controller/ScheduleController.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/dto/admin/AdminRequest.java
src/main/java/smash/teams/be/dto/schedule/ScheduleRequest.java
src/main/java/smash/teams/be/service/AdminService.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java
src/test/java/smash/teams/be/service/ScheduleServiceTest.java

PR: 승인 요청 구현 및 테스트 완료

---

src/main/java/smash/teams/be/controller/ScheduleController.java
src/main/java/smash/teams/be/dto/schedule/ScheduleRequest.java
src/main/java/smash/teams/be/dto/schedule/ScheduleResponse.java
src/main/java/smash/teams/be/model/schedule/Schedule.java
src/main/java/smash/teams/be/model/schedule/ScheduleRepository.java
src/main/java/smash/teams/be/model/user/User.java
src/main/java/smash/teams/be/model/user/UserRepository.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java
src/test/java/smash/teams/be/controller/UserControllerUnitTest.java
src/test/java/smash/teams/be/core/WithMockUser.java
src/test/java/smash/teams/be/core/WithMockUserFactory.java
src/test/java/smash/teams/be/core/WithMockUserWithTeam.java
src/test/java/smash/teams/be/core/WithMockUserWithTeamFactory.java
src/test/java/smash/teams/be/model/schedule/ScheduleRepositoryTest.java
src/test/java/smash/teams/be/service/ScheduleServiceTest.java

* 승인,거절하기 구현 완료
* 테스트 완료
* User 엔티티의  remain의 double로 변경 ( 반차의 경우 0.5 감소 )
* 이전 코드와 테스트 코드 수정 (커밋컨벤션을 지키지 못했습니다.)

PR: 승인,거절하기 구현 및 테스트 완료

---

src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/dto/user/UserRequest.java
src/main/java/smash/teams/be/dto/user/UserResponse.java
src/main/java/smash/teams/be/model/user/User.java
src/main/java/smash/teams/be/service/UserService.java
src/test/java/smash/teams/be/controller/UserControllerUnitTest.java
src/test/java/smash/teams/be/service/UserServiceTest.java

PR: 내정보 수정 구현 및 테스트 완료

---

src/main/java/smash/teams/be/service/UserService.java
src/test/java/smash/teams/be/controller/UserControllerTest.java

- 개인 정보 조회 성공 통합테스트 완료
- 개인 정보 조회 실패 통합테스트 완료
- rebase merge 전, 전체 테스트 성공

PR: 개인 정보 조회 통합테스트 완료

---

src/test/java/smash/teams/be/controller/UserControllerTest.java

- 내 정보 수정 성공 통합테스트 완료
- 내 정보 수정 실패 통합테스트 완료
- rebase merge 전, 전체 테스트 성공

PR: 내 정보 수정 통합 테스트 완료

---

src/test/java/smash/teams/be/controller/AdminControllerTest.java

PR: add 통합테스트 완료

---

src/test/java/smash/teams/be/controller/AdminControllerTest.java

PR: delete 통합테스트 완료

---

src/main/java/smash/teams/be/controller/ScheduleController.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/dto/schedule/ScheduleRequest.java
src/main/java/smash/teams/be/model/schedule/ScheduleRepository.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/test/java/smash/teams/be/controller/AdminControllerTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java
src/test/java/smash/teams/be/model/schedule/ScheduleRepositoryTest.java
src/test/java/smash/teams/be/service/ScheduleServiceTest.java

* 스케쥴 조회 (개인 & 관리자) 통합테스트
* 승인거절 통합테스트
* 일부 테스트 코드 수정

Test: 콘트롤러 통합테스트

---

src/main/java/smash/teams/be/controller/ScheduleController.java
src/test/java/smash/teams/be/controller/ScheduleControllerTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java

PR: orderSchedule apipath 수정

---

src/test/java/smash/teams/be/controller/ScheduleControllerTest.java

PR: makeScheduleRequest 통합테스트 완료

---

src/main/java/smash/teams/be/model/schedule/Schedule.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/main/java/smash/teams/be/service/UserService.java

* Service 메소드에 @Transactional 추가
* scheduleService에 최종승인 시 finishedAt 저장 추가

PR: Service에 @Transactional 추가

---

src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/core/auth/jwt/JwtProvider.java
src/main/java/smash/teams/be/core/auth/session/MyUserDetailsService.java
src/main/java/smash/teams/be/core/dummy/DataInit.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/dto/ResponseDTO.java
src/main/java/smash/teams/be/dto/user/UserRequest.java
src/main/java/smash/teams/be/dto/user/UserResponse.java
src/main/java/smash/teams/be/model/team/Team.java
src/main/java/smash/teams/be/model/user/User.java
src/main/java/smash/teams/be/model/user/UserRepository.java
src/main/java/smash/teams/be/service/UserService.java
src/main/resources/docs/api-docs.html
src/test/java/smash/teams/be/controller/AdminControllerTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java
src/test/java/smash/teams/be/controller/UserControllerTest.java
src/test/java/smash/teams/be/controller/UserControllerUnitTest.java
src/test/java/smash/teams/be/model/schedule/ScheduleRepositoryTest.java
src/test/java/smash/teams/be/model/user/UserRepositoryTest.java
src/test/java/smash/teams/be/service/UserServiceTest.java

login 통합테스트 완료
일부 테스트 관련 오류 해결

PR: login 통합테스트 완료

---

src/main/java/smash/teams/be/controller/ScheduleController.java
src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/core/dummy/DataInit.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/dto/user/UserRequest.java
src/main/java/smash/teams/be/dto/user/UserResponse.java
src/main/java/smash/teams/be/model/schedule/ScheduleRepository.java
src/main/java/smash/teams/be/model/team/TeamRepository.java
src/main/java/smash/teams/be/model/user/User.java
src/main/java/smash/teams/be/model/user/UserRepository.java
src/main/java/smash/teams/be/service/UserService.java
src/test/java/smash/teams/be/controller/AdminControllerTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerUnitTest.java
src/test/java/smash/teams/be/controller/UserControllerTest.java
src/test/java/smash/teams/be/controller/UserControllerUnitTest.java
src/test/java/smash/teams/be/model/schedule/ScheduleRepositoryTest.java
src/test/java/smash/teams/be/model/user/UserRepositoryTest.java
src/test/java/smash/teams/be/service/UserServiceTest.java

* 회원가입,탈퇴,이메일중복체크 구현
* 통합테스트 완료

PR: 회원가입,탈퇴,이메일중복체크 구현

---

src/main/java/smash/teams/be/core/auth/jwt/JwtProvider.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/application-test.yml

yml 파일 별 환경변수 셋팅
jwt 토큰 생성시 환경변수 값을 SECRET 변수에 주입받도록 코드 수정

PR: 배포 관련 설정 및 코드 수정

---

.github/deploy.yaml

Feat: Github Actions deploy.yaml 파일 추가

---

src/docs/asciidoc/api-docs.adoc
src/test/java/smash/teams/be/controller/AdminControllerTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerTest.java
src/test/java/smash/teams/be/controller/UserControllerTest.java

- REST API 문서
- 이미지 업로드 통합, 서비스 테스트 코드 제외
- push전 전체 테스트 성공
##스크린샷
##테스트 결과
##리뷰 요청 사항

PR: REST API 문서

---

scripts/gh_deploy.sh

Github Actions gh_deploy.sh 파일 추가

PR: Github Actions gh_deploy.sh 파일 추가

---

src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/dto/user/UserRequest.java
src/main/java/smash/teams/be/service/UserService.java
src/test/java/smash/teams/be/controller/UserControllerTest.java
src/test/java/smash/teams/be/service/UserServiceTest.java

* joinDTO, checkDuplicateEmail, withdraw 코드 수정
* 테스트 코드 수정

PR: method, dto 코드 수정

---

src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/core/dummy/DummyEntity.java
src/main/java/smash/teams/be/dto/user/UserRequest.java
src/main/java/smash/teams/be/service/UserService.java
src/test/java/smash/teams/be/controller/UserControllerTest.java
src/test/java/smash/teams/be/service/UserServiceTest.java

PR: main 브랜치 merge

---

src/main/resources/application.yml

배포를 위한 profile active prod로 변경

PR: 배포를 위한 profile active prod로 변경

---

.github/workflows/deploy.yaml

Style: deploy.yaml 오타 수정

---

.github/workflows/deploy.yml

PR: deploy.yaml 확장자 수정

---

src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/dto/user/UserRequest.java
src/main/java/smash/teams/be/service/UserService.java
src/test/java/smash/teams/be/controller/UserControllerTest.java
src/test/java/smash/teams/be/controller/UserControllerUnitTest.java
src/test/java/smash/teams/be/service/UserServiceTest.java

- imageUpload profileImage 필드 제거
- FE 요청사항 완료
- push 전, 전체 테스트 성공

PR: imageUpload profileImage 필드 제거

---

src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/core/auth/jwt/JwtProvider.java
src/main/java/smash/teams/be/dto/user/UserResponse.java
src/main/java/smash/teams/be/service/UserService.java
src/test/java/smash/teams/be/controller/UserControllerTest.java
src/test/java/smash/teams/be/service/UserServiceTest.java

LoginInfoOutDTO 변수 추가 및 로그인 성공시 기록이 DB에 남도록 수정

PR: LoginInfoOutDTO 변수 추가 및 로그인 성공시 기록이 DB에 남도록 수정

---

src/main/java/smash/teams/be/dto/user/UserResponse.java
src/test/java/smash/teams/be/controller/UserControllerUnitTest.java

- FindMyInfoOutDTO 코드 추가
- role, teamName, phoneNumber 필드 추가

PR: FindMyInfoOutDTO 코드 추가

---

src/main/java/smash/teams/be/controller/UserController.java
src/test/java/smash/teams/be/controller/UserControllerTest.java
src/test/java/smash/teams/be/controller/UserControllerUnitTest.java

- findMyInfo pathvariable 제거
- F5시 캐시정보 날라감 -> user 정보 저장 불가능

PR: findMyInfo pathvariable 제거

---

src/main/java/smash/teams/be/dto/user/UserResponse.java

PR: 내 정보 조회 remain 추가

---

src/docs/asciidoc/api-docs.adoc
src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/model/schedule/ScheduleRepository.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/main/java/smash/teams/be/service/UserService.java
src/main/resources/static/docs/api-docs.html
src/test/java/smash/teams/be/controller/AdminControllerTest.java
src/test/java/smash/teams/be/controller/ScheduleControllerTest.java
src/test/java/smash/teams/be/controller/UserControllerTest.java
src/test/java/smash/teams/be/model/schedule/ScheduleRepositoryTest.java
src/test/java/smash/teams/be/service/UserServiceTest.java

* Servic 수정
* join 이름중복 제거
* Repository 수정
* 내림차순 정렬 추가
* 테스트 수정
* api-docs 수정

PR: Service, Repository, 테스트, api-docs 수정

---

src/main/java/smash/teams/be/service/UserService.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml

PR: 프로필 이미지 서버 업로드 경로 변경

---

src/main/java/smash/teams/be/dto/schedule/ScheduleResponse.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/main/resources/static/docs/api-docs.html
src/test/java/smash/teams/be/controller/ScheduleControllerTest.java
src/test/java/smash/teams/be/service/ScheduleServiceTest.java

PR: 스케쥴관리 코드수정

---

src/docs/asciidoc/api-docs.adoc
src/main/resources/static/docs/api-docs.html
src/test/java/smash/teams/be/controller/UserControllerTest.java
upload/00624ad1-0eac-4b75-9d27-e6d5a2041c40_test-image.jpg

- 이미지 업로드 통합테스트 성공, RestDoc 재설정
- api-docs.html 빌드 

PR: 이미지 업로드 통합테스트 성공, RestDoc 재설정

---

build.gradle
src/main/java/smash/teams/be/core/advice/ExceptionAdvice.java
src/main/java/smash/teams/be/core/advice/LogAdvice.java
src/main/java/smash/teams/be/core/advice/ValidAdvice.java
src/main/resources/application-dev.yml
src/main/resources/application-prod.yml
src/main/resources/static/docs/api-docs.html
upload/7b00dcf9-c5b6-4681-8cf3-c39df3467820_test-image.jpg

sentry.io 관련 기능 추가
ValidAdvice가 delete 대신 patch에서 발동하도록 변경
에러 로그를 500번대 에러와 exception에 대해서만 db에 남기도록 변경
이미지 업로드 성공 테스트 관련 오류 해결

PR: sentry 기능 추가 및 일부 코드 수정

---

src/main/java/smash/teams/be/controller/ScheduleController.java
src/main/java/smash/teams/be/core/dummy/DataInit.java
src/main/java/smash/teams/be/model/schedule/ScheduleRepository.java
src/main/java/smash/teams/be/service/ScheduleService.java
src/main/java/smash/teams/be/service/UserService.java
src/test/java/smash/teams/be/service/ScheduleServiceTest.java
upload/1848765a-7ee2-4102-a6ef-d600f00c9636_test-image.jpg
upload/5273eebe-0d85-4dbd-bc0e-f4c54e48513c_test-image.jpg
upload/ded0edf2-e87b-416d-bdfe-79af7ecb75eb_test-image.jpg
upload/e18c0a71-4178-4412-8bdc-22f9461eb997_test-image.jpg

* 팀 추가, 삭제 구현 및 테스트 완료
* 테스트 코드 수정

PR: 개인스케쥴, 스케쥴 관리 수정

---

src/main/java/smash/teams/be/controller/UserController.java
src/main/java/smash/teams/be/dto/user/UserRequest.java
src/main/java/smash/teams/be/service/UserService.java
upload/b0bdb99a-e96a-407f-a954-e473d3e29455_test-image.jpg

PR: 개인정보 수정 해결

---

README.md

PR: README UI 추가

---

README.md

Docs: 송재근 개발일지 추가
